version: "1"

services:
  app:
    image: nadav:latest
    expose:
      - 9090
    deploy:
      replicas: 3

  nginx:
    image: nginx:latest
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    ports:
      - "9090:9090"

